server:
  port: 18002
spring:
  application:
    name: srping-redis-demo
  redis:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 60000
    host: 192.168.125.135
    port: 6379
  # 配置缓存策略
  cache:
    type: redis # 缓存类型指定为redis
    redis:
      use-key-prefix: true # 是否使用前缀
      key-prefix: cn.lyf.redis # 前缀名称
      time-to-live: 60000 # redis中缓存超时的时间，默认60000ms
      cache-null-values: true # 是否缓存null数据，默认是false
